-- 建表按字母序排列，先关闭外键检查避免引用顺序问题
SET FOREIGN_KEY_CHECKS = 0;
CREATE TABLE `asset_dependencies` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_by` bigint DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `deleted` bit(1) NOT NULL,
  `dependency_strength` enum('WEAK','MEDIUM','STRONG','CRITICAL') NOT NULL,
  `dependency_type` enum('NETWORK','DATABASE','SERVICE','APPLICATION','INFRASTRUCTURE','DATA_FLOW','AUTHENTICATION','STORAGE','MONITORING','BACKUP','OTHER') NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `is_critical` bit(1) NOT NULL,
  `port` int DEFAULT NULL,
  `protocol` varchar(50) DEFAULT NULL,
  `service_name` varchar(100) DEFAULT NULL,
  `source_asset_id` bigint NOT NULL,
  `status` enum('ACTIVE','INACTIVE','BROKEN','DEPRECATED') NOT NULL,
  `target_asset_id` bigint NOT NULL,
  `updated_time` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FKm93i0tgcewoaefu9v093dvpb4` (`source_asset_id`),
  KEY `FK981hp7oge50w69g55mewrbsie` (`target_asset_id`),
  CONSTRAINT `FK981hp7oge50w69g55mewrbsie` FOREIGN KEY (`target_asset_id`) REFERENCES `assets` (`id`),
  CONSTRAINT `FKm93i0tgcewoaefu9v093dvpb4` FOREIGN KEY (`source_asset_id`) REFERENCES `assets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `asset_detections` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_id` bigint NOT NULL,
  `banner` text,
  `created_time` datetime(6) NOT NULL,
  `details` text,
  `end_time` datetime(6) DEFAULT NULL,
  `error_message` text,
  `http_status_code` int DEFAULT NULL,
  `port` int DEFAULT NULL,
  `response_time` bigint DEFAULT NULL,
  `result` enum('ONLINE','OFFLINE','TIMEOUT','UNREACHABLE','FILTERED','UNKNOWN') DEFAULT NULL,
  `start_time` datetime(6) NOT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','TIMEOUT','CANCELLED') NOT NULL,
  `target` varchar(500) NOT NULL,
  `type` enum('PING','TCP_PORT','HTTP_SERVICE','HTTPS_SERVICE','SSH_SERVICE','DATABASE_SERVICE','CUSTOM_PORT') NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `asset_discovery_results` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `asset_id` bigint DEFAULT NULL,
  `confidence_score` decimal(3,2) DEFAULT NULL,
  `correlation_status` enum('NEW','MATCHED','UPDATED','IGNORED') NOT NULL,
  `device_type` varchar(100) DEFAULT NULL,
  `discovered_time` datetime(6) NOT NULL,
  `hostname` varchar(255) DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `is_alive` bit(1) NOT NULL,
  `mac_address` varchar(17) DEFAULT NULL,
  `open_ports` json DEFAULT NULL,
  `operating_system` varchar(200) DEFAULT NULL,
  `raw_data` json DEFAULT NULL,
  `response_time` int DEFAULT NULL,
  `services` json DEFAULT NULL,
  `target` varchar(500) NOT NULL,
  `task_id` bigint NOT NULL,
  `vendor` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `asset_discovery_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_by` bigint NOT NULL,
  `created_time` datetime(6) NOT NULL,
  `deleted` bit(1) NOT NULL,
  `description` text,
  `last_run_time` datetime(6) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `next_run_time` datetime(6) DEFAULT NULL,
  `progress` decimal(5,2) DEFAULT NULL,
  `scan_options` json DEFAULT NULL,
  `scan_ports` varchar(1000) DEFAULT NULL,
  `scan_type` enum('PING_SWEEP','PORT_SCAN','SERVICE_DETECTION','FULL_SCAN') NOT NULL,
  `schedule_config` json DEFAULT NULL,
  `schedule_type` enum('ONCE','DAILY','WEEKLY','MONTHLY','CUSTOM') NOT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED') NOT NULL,
  `target_type` enum('IP_RANGE','SUBNET','DOMAIN','URL_LIST','CUSTOM') NOT NULL,
  `targets` text NOT NULL,
  `updated_time` datetime(6) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `asset_fingerprints` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `active` bit(1) NOT NULL,
  `asset_id` bigint NOT NULL,
  `banner` text,
  `confidence` int NOT NULL,
  `created_time` datetime(6) NOT NULL,
  `error_page` text,
  `extra_info` text,
  `http_headers` text,
  `method` enum('HTTP_HEADER','SERVER_BANNER','ERROR_PAGE','SIGNATURE_FILE','PAGE_CONTENT','COOKIE','REDIRECT','SSL_CERTIFICATE','PORT_SERVICE','FAVICON','ROBOTS_TXT','SITEMAP','META_TAG','JAVASCRIPT','CSS','CUSTOM_RULE') DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `page_title` varchar(500) DEFAULT NULL,
  `port` int DEFAULT NULL,
  `protocol` varchar(20) DEFAULT NULL,
  `signature` text,
  `signature_file` varchar(500) DEFAULT NULL,
  `type` enum('WEB_SERVER','APPLICATION_SERVER','DATABASE','OPERATING_SYSTEM','WEB_FRAMEWORK','CMS','PROGRAMMING_LANGUAGE','MIDDLEWARE','LOAD_BALANCER','WAF','CDN','CACHE','MONITORING','SECURITY_PRODUCT','NETWORK_DEVICE','IOT_DEVICE','OTHER') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vendor` varchar(100) DEFAULT NULL,
  `version` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `assets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deleted` bit(1) NOT NULL,
  `description` text,
  `domain` varchar(255) DEFAULT NULL,
  `importance` enum('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT NULL,
  `ip_address` varchar(45) NOT NULL,
  `last_scan_time` datetime(6) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `notes` text,
  `operating_system` varchar(100) DEFAULT NULL,
  `owner_id` bigint DEFAULT NULL,
  `port` int DEFAULT NULL,
  `project_id` bigint DEFAULT NULL,
  `protocol` varchar(20) DEFAULT NULL,
  `risk_score` double DEFAULT NULL,
  `service` varchar(100) DEFAULT NULL,
  `status` enum('ACTIVE','INACTIVE','MAINTENANCE','DECOMMISSIONED') NOT NULL,
  `tags` varchar(500) DEFAULT NULL,
  `type` enum('SERVER','WORKSTATION','NETWORK_DEVICE','DATABASE','WEB_APPLICATION','MOBILE_APPLICATION','IOT_DEVICE','CLOUD_SERVICE','OTHER') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vendor` varchar(100) DEFAULT NULL,
  `version` varchar(50) DEFAULT NULL,
  `vulnerability_count` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `baseline_check_items` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `actual_value` text,
  `category` varchar(100) DEFAULT NULL,
  `check_command` text,
  `check_details` text,
  `check_time` datetime(6) DEFAULT NULL,
  `created_time` datetime(6) DEFAULT NULL,
  `description` text,
  `error_message` text,
  `expected_value` text,
  `item_code` varchar(50) NOT NULL,
  `item_name` varchar(200) NOT NULL,
  `reference` varchar(500) DEFAULT NULL,
  `remediation` text,
  `result` enum('PASS','FAIL','WARNING','NOT_APPLICABLE') DEFAULT NULL,
  `severity` enum('CRITICAL','HIGH','MEDIUM','LOW','INFO') NOT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','SKIPPED','ERROR') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `baseline_check_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK2l42ni2ylib59ppwtv91mvah` (`baseline_check_id`),
  CONSTRAINT `FK2l42ni2ylib59ppwtv91mvah` FOREIGN KEY (`baseline_check_id`) REFERENCES `baseline_checks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `baseline_checks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `check_config` text,
  `check_type` enum('SYSTEM_SECURITY','NETWORK_SECURITY','DATABASE_SECURITY','WEB_SECURITY','MIDDLEWARE_SECURITY','CLOUD_SECURITY','CUSTOM') NOT NULL,
  `compliance_score` double DEFAULT NULL,
  `created_time` datetime(6) DEFAULT NULL,
  `deleted` bit(1) DEFAULT NULL,
  `description` text,
  `end_time` datetime(6) DEFAULT NULL,
  `error_message` text,
  `failed_items` int DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `passed_items` int DEFAULT NULL,
  `progress` int DEFAULT NULL,
  `report_path` varchar(500) DEFAULT NULL,
  `result` enum('PASS','FAIL','WARNING','PARTIAL') DEFAULT NULL,
  `skipped_items` int DEFAULT NULL,
  `start_time` datetime(6) DEFAULT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED') NOT NULL,
  `total_items` int DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `warning_items` int DEFAULT NULL,
  `asset_id` bigint DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKpg2hlwjcunydga5yysrm853j4` (`asset_id`),
  KEY `FK1g5dprq7whvta6j8oii9imfi5` (`created_by`),
  CONSTRAINT `FK1g5dprq7whvta6j8oii9imfi5` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`),
  CONSTRAINT `FKpg2hlwjcunydga5yysrm853j4` FOREIGN KEY (`asset_id`) REFERENCES `assets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `project_members` (
  `project_id` bigint NOT NULL,
  `user_id` bigint NOT NULL,
  KEY `FKgul2el0qjk5lsvig3wgajwm77` (`user_id`),
  KEY `FKdki1sp2homqsdcvqm9yrix31g` (`project_id`),
  CONSTRAINT `FKdki1sp2homqsdcvqm9yrix31g` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`),
  CONSTRAINT `FKgul2el0qjk5lsvig3wgajwm77` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `projects` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `budget` decimal(12,2) DEFAULT NULL,
  `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `department` varchar(100) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `end_date` datetime(6) DEFAULT NULL,
  `name` varchar(200) NOT NULL,
  `priority` enum('LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
  `start_date` datetime(6) DEFAULT NULL,
  `status` enum('PLANNING','ACTIVE','ON_HOLD','COMPLETED','CANCELLED') NOT NULL,
  `tags` varchar(500) DEFAULT NULL,
  `updated_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `owner_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKmueqy6cpcwpfl8gnnag4idjt9` (`owner_id`),
  CONSTRAINT `FKmueqy6cpcwpfl8gnnag4idjt9` FOREIGN KEY (`owner_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `scan_configs` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_time` datetime(6) NOT NULL,
  `custom_scripts` text,
  `deleted` bit(1) NOT NULL,
  `description` text,
  `enabled` bit(1) NOT NULL,
  `exclude_ports` varchar(200) DEFAULT NULL,
  `exclude_vuln_types` text,
  `include_vuln_types` text,
  `is_default` bit(1) NOT NULL,
  `max_concurrency` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `os_detection` bit(1) NOT NULL,
  `parameters` text,
  `port_range` varchar(200) DEFAULT NULL,
  `scan_depth` enum('LIGHT','NORMAL','DEEP','COMPREHENSIVE') DEFAULT NULL,
  `scan_engine` enum('NESSUS','OPENVAS','AWVS','NUCLEI','NMAP','INTERNAL') NOT NULL,
  `scan_policy` text,
  `scan_template` enum('QUICK_SCAN','FULL_SCAN','WEB_APP_SCAN','NETWORK_SCAN','COMPLIANCE_SCAN','CUSTOM') DEFAULT NULL,
  `scan_type` enum('PORT_SCAN','WEB_SCAN','SYSTEM_SCAN','COMPREHENSIVE_SCAN','CUSTOM_SCAN') NOT NULL,
  `scan_udp` bit(1) NOT NULL,
  `script_scan` bit(1) NOT NULL,
  `service_detection` bit(1) NOT NULL,
  `timeout_minutes` int DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vulnerability_scan` bit(1) NOT NULL,
  `web_app_scan` bit(1) NOT NULL,
  `created_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKcbsgoff3o2txud2orw57a1jjm` (`created_by`),
  CONSTRAINT `FKcbsgoff3o2txud2orw57a1jjm` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `scan_results` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `confirmation_status` enum('UNCONFIRMED','CONFIRMED','FALSE_POSITIVE','DUPLICATE') DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `cve_id` varchar(50) DEFAULT NULL,
  `cvss_score` double DEFAULT NULL,
  `cvss_vector` varchar(200) DEFAULT NULL,
  `deleted` bit(1) NOT NULL,
  `discovered_time` datetime(6) NOT NULL,
  `external_result_id` varchar(100) DEFAULT NULL,
  `false_positive` bit(1) NOT NULL,
  `plugin_family` varchar(100) DEFAULT NULL,
  `plugin_id` varchar(50) DEFAULT NULL,
  `plugin_name` varchar(200) DEFAULT NULL,
  `proof` text,
  `raw_data` longtext,
  `reference_links` text,
  `request` text,
  `response` text,
  `risk_level` enum('CRITICAL','HIGH','MEDIUM','LOW','NONE') DEFAULT NULL,
  `severity` enum('CRITICAL','HIGH','MEDIUM','LOW','INFO') NOT NULL,
  `solution` text,
  `status` enum('OPEN','FIXED','ACCEPTED','IGNORED','RETEST') NOT NULL,
  `target_host` varchar(255) NOT NULL,
  `target_port` int DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vulnerability_description` text,
  `vulnerability_name` varchar(500) NOT NULL,
  `vulnerability_type` varchar(100) DEFAULT NULL,
  `asset_id` bigint DEFAULT NULL,
  `scan_task_id` bigint NOT NULL,
  `vulnerability_id` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FKsr2mmwu72xrgdxxw7q4gj5jib` (`asset_id`),
  KEY `FKdwjdj8qxpjm4wivvp8vxvahj` (`scan_task_id`),
  KEY `FK42ywflvkpbnqt4vclc66li6db` (`vulnerability_id`),
  CONSTRAINT `FK42ywflvkpbnqt4vclc66li6db` FOREIGN KEY (`vulnerability_id`) REFERENCES `vulnerabilities` (`id`),
  CONSTRAINT `FKdwjdj8qxpjm4wivvp8vxvahj` FOREIGN KEY (`scan_task_id`) REFERENCES `scan_tasks` (`id`),
  CONSTRAINT `FKsr2mmwu72xrgdxxw7q4gj5jib` FOREIGN KEY (`asset_id`) REFERENCES `assets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `scan_task_targets` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `completed_time` datetime(6) DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `error_message` text,
  `high_risk_count` int DEFAULT NULL,
  `info_risk_count` int DEFAULT NULL,
  `low_risk_count` int DEFAULT NULL,
  `medium_risk_count` int DEFAULT NULL,
  `progress` int DEFAULT NULL,
  `result_summary` text,
  `start_time` datetime(6) DEFAULT NULL,
  `status` enum('PENDING','RUNNING','COMPLETED','FAILED','SKIPPED') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vulnerability_count` int DEFAULT NULL,
  `asset_id` bigint NOT NULL,
  `scan_task_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK5q207qkesfhq4svxjgpdets68` (`asset_id`),
  KEY `FK2jch5gwcfvngh9v477fha8ur4` (`scan_task_id`),
  CONSTRAINT `FK2jch5gwcfvngh9v477fha8ur4` FOREIGN KEY (`scan_task_id`) REFERENCES `scan_tasks` (`id`),
  CONSTRAINT `FK5q207qkesfhq4svxjgpdets68` FOREIGN KEY (`asset_id`) REFERENCES `assets` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `scan_tasks` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `actual_start_time` datetime(6) DEFAULT NULL,
  `completed_time` datetime(6) DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `deleted` bit(1) NOT NULL,
  `description` text,
  `error_message` text,
  `external_task_id` varchar(100) DEFAULT NULL,
  `high_risk_count` int DEFAULT NULL,
  `info_risk_count` int DEFAULT NULL,
  `low_risk_count` int DEFAULT NULL,
  `medium_risk_count` int DEFAULT NULL,
  `name` varchar(100) NOT NULL,
  `port_count` int DEFAULT NULL,
  `progress` int DEFAULT NULL,
  `project_id` bigint NOT NULL,
  `result_file_path` varchar(500) DEFAULT NULL,
  `scan_config_id` bigint DEFAULT NULL,
  `scan_engine_type` enum('NESSUS','OPENVAS','AWVS','NUCLEI','NMAP','INTERNAL') NOT NULL,
  `scan_parameters` text,
  `scan_result` longtext,
  `scan_template` enum('QUICK_SCAN','FULL_SCAN','WEB_APP_SCAN','NETWORK_SCAN','COMPLIANCE_SCAN','CUSTOM') DEFAULT NULL,
  `scan_type` enum('PORT_SCAN','WEB_SCAN','SYSTEM_SCAN','COMPREHENSIVE_SCAN','CUSTOM_SCAN') NOT NULL,
  `scheduled_start_time` datetime(6) DEFAULT NULL,
  `service_count` int DEFAULT NULL,
  `status` enum('CREATED','QUEUED','RUNNING','PAUSED','COMPLETED','FAILED','CANCELLED','TIMEOUT') NOT NULL,
  `target_count` int DEFAULT NULL,
  `total_vulnerability_count` int DEFAULT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vulnerability_count` int DEFAULT NULL,
  `created_by` bigint DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK21qnvmn2yh7kpfojt1w40l79d` (`created_by`),
  CONSTRAINT `FK21qnvmn2yh7kpfojt1w40l79d` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `users` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `avatar_url` varchar(255) DEFAULT NULL,
  `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `deleted` bit(1) NOT NULL DEFAULT b'0',
  `department` varchar(100) DEFAULT NULL,
  `email` varchar(100) NOT NULL,
  `full_name` varchar(100) DEFAULT NULL,
  `last_login_time` datetime(6) DEFAULT NULL,
  `notes` text,
  `password` varchar(255) NOT NULL,
  `phone` varchar(20) DEFAULT NULL,
  `position` varchar(100) DEFAULT NULL,
  `role` enum('ADMIN','MANAGER','ANALYST','VIEWER','USER') NOT NULL,
  `status` enum('ACTIVE','INACTIVE','LOCKED') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `username` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UK_6dotkott2kjsp8vw4d0m25fb7` (`email`),
  UNIQUE KEY `UK_r43af9ap4edm43mmtq01oddj6` (`username`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `vulnerabilities` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `affected_systems` text,
  `asset_id` bigint DEFAULT NULL,
  `assignee_id` bigint DEFAULT NULL,
  `category` varchar(50) DEFAULT NULL,
  `created_time` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `cve_id` varchar(20) DEFAULT NULL,
  `cvss_score` decimal(3,1) DEFAULT NULL,
  `deleted` bit(1) NOT NULL,
  `description` text,
  `discovered_date` date NOT NULL,
  `due_date` date DEFAULT NULL,
  `plugin_id` varchar(100) DEFAULT NULL,
  `port` int DEFAULT NULL,
  `project_id` bigint NOT NULL,
  `proof` text,
  `protocol` varchar(20) DEFAULT NULL,
  `reference_links` text,
  `reporter_id` bigint NOT NULL,
  `reproduction_steps` text,
  `resolved_date` date DEFAULT NULL,
  `risk_level` enum('LOW','MEDIUM','HIGH','CRITICAL') DEFAULT NULL,
  `scan_engine` varchar(50) DEFAULT NULL,
  `scan_task_id` bigint DEFAULT NULL,
  `severity` enum('INFO','LOW','MEDIUM','HIGH','CRITICAL') NOT NULL,
  `solution` text,
  `source` enum('MANUAL','SCAN','IMPORT','API') DEFAULT NULL,
  `status` enum('OPEN','IN_PROGRESS','RESOLVED','CLOSED','REOPENED') NOT NULL,
  `title` varchar(200) NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `url` varchar(500) DEFAULT NULL,
  `verification_status` enum('PENDING','VERIFIED','FALSE_POSITIVE') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
CREATE TABLE `vulnerability_status_changes` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `approval_comment` text,
  `approval_time` datetime(6) DEFAULT NULL,
  `approver_id` bigint DEFAULT NULL,
  `created_time` datetime(6) NOT NULL,
  `from_status` enum('OPEN','IN_PROGRESS','RESOLVED','CLOSED','REOPENED') NOT NULL,
  `reason` text,
  `request_time` datetime(6) NOT NULL,
  `requester_id` bigint NOT NULL,
  `status` enum('PENDING','APPROVED','REJECTED') NOT NULL,
  `to_status` enum('OPEN','IN_PROGRESS','RESOLVED','CLOSED','REOPENED') NOT NULL,
  `updated_time` datetime(6) DEFAULT NULL,
  `vulnerability_id` bigint NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
SET FOREIGN_KEY_CHECKS = 1;
